<a href="https://colab.research.google.com/github/Dr-Rao-Patike/DL-2024-25/blob/main/deep_learning_l2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)


Scalar value: 5


In [ ]:
# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)


Vector values: [1 2 3]


In [ ]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)
